# Generated by Django 5.2.6 on 2025-09-20 13:30

import django.db.models.deletion
import habits.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=255)),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку"
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, help_text="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity_days",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[habits.validators.validate_periodicity_days],
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=60,
                        validators=[habits.validators.validate_duration_seconds_le_120],
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("last_notified_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_to",
                        to="habits.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
